FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN mkdir /backend_app
WORKDIR /backend_app

COPY . .

RUN pip install -U pip 
RUN pip install -r dependencies/requirements_prod.txt

RUN chmod a+x scripts/docker.sh

CMD ["./scripts/docker.sh", "backend"]
