version: '3'

services:

  postgres:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB

  postgres_test:
    image: postgres:latest
    container_name: postgres_test_db
    ports:
      - "5444:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=calendarapi_test

  web:
    image: calendarapi
    build: .
    command: gunicorn -b 0.0.0.0:5000 --reload calendarapi.wsgi:app
    env_file:
      - ./.env
    environment:
      - DATABASE_URI=$DATABASE_URI
      - CELERY_BROKER_URL=$CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND_URL=$CELERY_RESULT_BACKEND_URL
    volumes:
      - ./calendarapi:/code/calendarapi
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  redis:
    image: redis

  celery:
    image: calendarapi
    command: "celery -A calendarapi.celery_app:app worker -B --loglevel=info"
    env_file:
      - ./.env
    volumes:
      - .:/code
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=$CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND_URL=$CELERY_BROKER_URL

  flower:
    image: mher/flower
    env_file:
      - ./.env
    command: "celery --broker=$CELERY_BROKER_URL flower  --persistent=True --basic_auth=$ADMIN_DEFAULT_LOGIN:$ADMIN_DEFAULT_PASSWORD"
    ports:
      - "5555:5555"
    depends_on:
      - redis
