"""empty message

Revision ID: 36e09e38a9ba
Revises: 7c12027b44f8
Create Date: 2023-12-13 14:42:46.607077

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "36e09e38a9ba"
down_revision = "7c12027b44f8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("appointments", schema=None) as batch_op:
        batch_op.drop_column("city")

    with op.batch_alter_table("lawyers", schema=None) as batch_op:
        batch_op.drop_column("surname")

    with op.batch_alter_table("visitors", schema=None) as batch_op:
        batch_op.alter_column(
            "name", existing_type=sa.VARCHAR(length=100), nullable=True
        )
        batch_op.alter_column(
            "email", existing_type=sa.VARCHAR(length=100), nullable=True
        )
        batch_op.drop_constraint("visitors_email_key", type_="unique")
        batch_op.drop_column("surname")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("visitors", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "surname", sa.VARCHAR(length=100), autoincrement=False, nullable=False
            )
        )
        batch_op.create_unique_constraint("visitors_email_key", ["email"])
        batch_op.alter_column(
            "email", existing_type=sa.VARCHAR(length=100), nullable=False
        )
        batch_op.alter_column(
            "name", existing_type=sa.VARCHAR(length=100), nullable=False
        )

    with op.batch_alter_table("lawyers", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "surname", sa.VARCHAR(length=100), autoincrement=False, nullable=False
            )
        )

    with op.batch_alter_table("appointments", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("city", sa.VARCHAR(), autoincrement=False, nullable=False)
        )

    # ### end Alembic commands ###
