"""empty message

Revision ID: 6f3f4f4166a0
Revises: a88962a59ab9
Create Date: 2024-01-13 15:50:04.065097

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6f3f4f4166a0"
down_revision = "a88962a59ab9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("clients", schema=None) as batch_op:
        batch_op.drop_constraint("clients_link_key", type_="unique")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("clients", schema=None) as batch_op:
        batch_op.create_unique_constraint("clients_link_key", ["link"])

    # ### end Alembic commands ###
