"""empty message

Revision ID: 7b07f1d3d879
Revises: 3665feecc980
Create Date: 2023-12-01 16:25:31.330762

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7b07f1d3d879"
down_revision = "3665feecc980"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contacts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("contact_type", sa.String(length=100), nullable=False),
        sa.Column("value", sa.String(length=2000), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("contact_type"),
    )
    op.create_table(
        "news",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.Column("photo_path", sa.String(length=300), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("description"),
    )
    with op.batch_alter_table("cities", schema=None) as batch_op:
        batch_op.add_column(sa.Column("address", sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cities", schema=None) as batch_op:
        batch_op.drop_column("address")

    op.drop_table("news")
    op.drop_table("contacts")
    # ### end Alembic commands ###
