"""empty message

Revision ID: 9db92ba20edd
Revises: 36e09e38a9ba
Create Date: 2023-12-15 12:04:44.424245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9db92ba20edd"
down_revision = "36e09e38a9ba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.alter_column(
            "position", existing_type=sa.VARCHAR(length=100), nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.alter_column(
            "position", existing_type=sa.VARCHAR(length=100), nullable=False
        )

    # ### end Alembic commands ###
