"""empty message

Revision ID: b8b3f4413403
Revises: 9db92ba20edd
Create Date: 2023-12-15 20:16:40.933432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b8b3f4413403"
down_revision = "9db92ba20edd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("layers_to_cities")
    with op.batch_alter_table("cities", schema=None) as batch_op:
        batch_op.alter_column(
            "address",
            existing_type=sa.VARCHAR(length=500),
            type_=sa.String(length=200),
            nullable=False,
        )

    with op.batch_alter_table("contacts", schema=None) as batch_op:
        batch_op.alter_column(
            "value",
            existing_type=sa.VARCHAR(length=2000),
            type_=sa.String(length=500),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("contacts", schema=None) as batch_op:
        batch_op.alter_column(
            "value",
            existing_type=sa.String(length=500),
            type_=sa.VARCHAR(length=2000),
            existing_nullable=True,
        )

    with op.batch_alter_table("cities", schema=None) as batch_op:
        batch_op.alter_column(
            "address",
            existing_type=sa.String(length=200),
            type_=sa.VARCHAR(length=500),
            nullable=True,
        )

    op.create_table(
        "layers_to_cities",
        sa.Column("lawyer_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("city_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["city_id"], ["cities.id"], name="layers_to_cities_city_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["lawyer_id"], ["lawyers.id"], name="layers_to_cities_lawyer_id_fkey"
        ),
        sa.PrimaryKeyConstraint("lawyer_id", "city_id", name="layers_to_cities_pkey"),
    )
    # ### end Alembic commands ###
