"""empty message

Revision ID: c3c4e83b95ff
Revises: 5ee929df2187
Create Date: 2023-12-20 17:18:27.165998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c3c4e83b95ff"
down_revision = "5ee929df2187"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("appointments", schema=None) as batch_op:
        batch_op.add_column(sa.Column("visitor_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, "visitors", ["visitor_id"], ["id"])
        batch_op.drop_column("visitor")

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("is_superuser")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_superuser", sa.BOOLEAN(), autoincrement=False, nullable=True)
        )

    with op.batch_alter_table("appointments", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("visitor", sa.VARCHAR(), autoincrement=False, nullable=False)
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("visitor_id")

    # ### end Alembic commands ###
