"""empty message

Revision ID: d0bbda3ba2bc
Revises: c3c4e83b95ff
Create Date: 2023-12-26 16:59:55.916806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d0bbda3ba2bc"
down_revision = "c3c4e83b95ff"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("news", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("specialization_name", sa.String(length=255), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("news", schema=None) as batch_op:
        batch_op.drop_column("specialization_name")

    # ### end Alembic commands ###
