"""empty message

Revision ID: e032f2f9aca9
Revises: 7b07f1d3d879
Create Date: 2023-12-01 23:40:47.302443

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e032f2f9aca9"
down_revision = "7b07f1d3d879"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("position", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.Column("photo_path", sa.String(length=300), nullable=False),
        sa.Column("created_at", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("description"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reviews")
    # ### end Alembic commands ###
