"""empty message

Revision ID: e0f7704afea0
Revises: 6f3f4f4166a0
Create Date: 2024-01-31 18:33:18.362998

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e0f7704afea0"
down_revision = "6f3f4f4166a0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lawyers", schema=None) as batch_op:
        batch_op.drop_constraint("lawyers_lawyer_mail_key", type_="unique")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lawyers", schema=None) as batch_op:
        batch_op.create_unique_constraint("lawyers_lawyer_mail_key", ["lawyer_mail"])

    # ### end Alembic commands ###
