"""empty message

Revision ID: edf9785f07ac
Revises: e0f7704afea0
Create Date: 2024-02-06 18:58:18.924485

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "edf9785f07ac"
down_revision = "e0f7704afea0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("about_company", schema=None) as batch_op:
        batch_op.add_column(sa.Column("first_slider_photo_path", sa.String(length=300)))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("about_company", schema=None) as batch_op:
        batch_op.drop_column("first_slider_photo_path")

    # ### end Alembic commands ###
