"""empty message

Revision ID: f5ed6053354c
Revises: 4c5871602ef1
Create Date: 2023-12-12 13:37:42.620396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5ed6053354c'
down_revision = '4c5871602ef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pro_bono',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_path', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pro_bono')
    # ### end Alembic commands ###
