"""empty message

Revision ID: f6a43cef06e6
Revises: 034caa589da3
Create Date: 2023-12-16 12:47:45.061878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f6a43cef06e6"
down_revision = "034caa589da3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hero_block",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slogan", sa.String(length=30), nullable=False),
        sa.Column("left_text", sa.String(length=200), nullable=False),
        sa.Column("right_text", sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("about_company", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("main_page_photo_path", sa.String(length=300), nullable=False)
        )
        batch_op.add_column(
            sa.Column("our_team_page_photo_path", sa.String(length=300), nullable=False)
        )
        batch_op.add_column(
            sa.Column("main_page_description", sa.String(length=500), nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "our_team_page_description", sa.String(length=3000), nullable=False
            )
        )
        batch_op.drop_column("photo_path")
        batch_op.drop_column("description")
        batch_op.drop_column("title")

    with op.batch_alter_table("user_security", schema=None) as batch_op:
        batch_op.create_foreign_key(
            None, "users", ["user_id"], ["id"], ondelete="CASCADE"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_security", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")

    with op.batch_alter_table("about_company", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "title", sa.VARCHAR(length=100), autoincrement=False, nullable=False
            )
        )
        batch_op.add_column(
            sa.Column(
                "description",
                sa.VARCHAR(length=3000),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "photo_path",
                sa.VARCHAR(length=300),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.drop_column("our_team_page_description")
        batch_op.drop_column("main_page_description")
        batch_op.drop_column("our_team_page_photo_path")
        batch_op.drop_column("main_page_photo_path")

    op.drop_table("hero_block")
    # ### end Alembic commands ###
